name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths-ignore:
      - .github/
jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: "${{ steps.release.outputs.new_release_published }}"
      new_release_version: "${{ steps.release.outputs.new_release_version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_RUNNER_TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        # with:
        #   install: true
      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      #     cache: npm
      # - name: NPM Clean Install
      #   run: npm ci
      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_RUNNER_TOKEN }}
          DOCKER_REGISTRY_USER: ${{ secrets.QUAY_USER }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        with:
          semantic_version: 19.0.5
          ci: false
          branches: "['main']"
          extra_plugins: |
            conventional-changelog-conventionalcommits
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/github
            @codedependant/semantic-release-docker
      - if: steps.release.outputs.new_release_published == 'true'
        name: Checkout helm chart
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/chart-${{ github.event.repository.name }}
          token: ${{ secrets.GIT_RUNNER_TOKEN }}
          ref: main
      - if: steps.release.outputs.new_release_published == 'true'
        name: Update appVersion
        shell: bash
        run: |
          sed -i "0,/appVersion:.*/s//appVersion: \"${{ steps.release.outputs.new_release_version }}\"/g" chart/Chart.yaml
      - if: steps.release.outputs.new_release_published == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GIT_RUNNER_TOKEN }}
          title: ${{ github.event.pull_request.title }}
          body: 'Automated changes triggered by [pull request](${{ github.event.pull_request._links.html.href }})<br />${{ github.event.pull_request.body }}'
          commit-message: ${{ github.event.pull_request.title }}
          branch: 'main${{ steps.release.outputs.new_release_version }}'
          delete-branch: true
          labels: automerge
